### PR TITLE
BugFix: PDivider not very visible

### PR DESCRIPTION
**Pull request by pleek91**
# Description
Matching the colors from PCard

Before
image

After
image

### CODE REVIEW

**Comment by znicholasbrown** [comment]
Hm, this was intentional tbh, it's meant to be lower-contrast than content as a visual rest but not a hard break necessarily. That said, I don't feel strongly about the change (except the change to `foreground`, that makes sense)

**Comment by pleek91** [comment]
Its just not even noticeable in some contexts currently which is what I'm trying to solve. And if it matches the card in light mode I think it should match the card in dark mode as well.

**Comment by znicholasbrown** [comment]
Hm ok I see your point; I don't think the card border is the correct standard here since this is for content. Tested with `bg-foreground-50` and `dark:bg-foreground-100` and thought the results were decent, wdyt?

**Comment by pleek91** [comment]
Looks good on light mode but personally I can barely even see the divider on dark mode. Like I cannot see if except that I'm looking for it

image

**Comment by pleek91** [comment]
@znicholasbrown never mind. That screenshot is incorrect. Yes those colors look good to me. Updated 👍

**Review by znicholasbrown — APPROVED** [review]
ty!

**Pull request merged**
