### PR TITLE
add root background colors

### PR DESCRIPTION
**Pull request by brandonreid**
This adds the root background colors. Some bg colors, for things like inputs and buttons, will have their own semantic tokens in fallowing PR's, at which point I'll remove the previous custom bg utilities in favor of the new ones.

### CODE REVIEW

**Comment by pleek91** [comment]
@brandonreid this PR needs to be against the `redesign` branch and not `main`

**Comment by brandonreid** [comment]
> @brandonreid this PR needs to be against the `redesign` branch and not `main`

Good looking out @pleek91 , fixed

**Comment by pleek91** [comment]
@brandonreid as part of this PR I'd expect to see the existing background colors removed (both background and probably foreground).

**Comment by brandonreid** [comment]
> @brandonreid as part of this PR I'd expect to see the existing background colors removed (both background and probably foreground).

Yeah, in the PR description I address that. There are background colors for things like inputs, states, and interactive elements that will have their own tokens. I can do all backgrounds at once, will just be a larger PR? Or I figured I'll address removing those once the component tokens have made it through.

**Review by pleek91 — APPROVED** [review]

**Pull request merged**
